replicaCount: 1

image:
  repository: "docker.io/username/myreactapp"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  host: "react.example.com"
  path: "/"
  pathType: "Prefix"
  tls:
    enabled: true
    secretName: "react-boilerplate-tls"
