apiVersion: v1
kind: Service
metadata:
  name: { { include "react-app.fullname" . } }
  labels: { { - include "react-app.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: { { include "react-app.name" . } }
    app.kubernetes.io/instance: { { .Release.Name } }
